#!/usr/bin/python3

import json
import sys

from datetime import datetime
from sugscrape.event import Event
from zoneinfo import ZoneInfo

now = datetime.now().astimezone(ZoneInfo("localtime"))

# Parse the SUG "available" report on stdin
page = json.load(sys.stdin)

available = []
for signup in page["data"]["signup"]:
    available.append(Event(signup))

month = "December"
for event in sorted(available):
    if event.month() != month:
        month = event.month()
        print("\n\n" + month + "\n")
    if event.date < now:
        continue
    print(" " + str(event))
