#!/usr/bin/python3

import os
import pprint
import requests

from dateutil import parser
from zoneinfo import ZoneInfo

# This is the 2025 trustee signup
page = requests.get("https://api.signupgenius.com/v2/k/signups/report/available/53310616/?user_key=" + os.environ["SUG_API_KEY"])
page.raise_for_status()

available = []
for signup in page.json()["data"]["signup"]:
    available.append(signup["startdatestring"])

available.sort()

for event in available:
    parsed_date = parser.parse(event).astimezone(ZoneInfo('localtime'))
    print(parsed_date.strftime("%A %B %d"))
